name: 'Run tests'

on:
  push:
    branches-ignore:
      - main

permissions: write-all

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-20.04
    steps:
      - name: 'Run tests'
        run: |
          printenv
          echo "Dummy tests"
